# Generated by Django 4.0.3 on 2023-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_alter_item_options_remove_item_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
