# Generated by Django 4.0.3 on 2023-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_files/'),
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
